# Generated by Django 4.2 on 2026-01-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
